set(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_CONTACT "enakaev.aleksey@yandex.ru")
set(CPACK_PACKAGE_VENDOR "Enakaev Aleksey")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_PACKAGING_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")
set(CPACK_PACKAGE_CHECKSUM SHA512)
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

set(DEBIAN_CONTROL_POSTINST_TEMPLATE ${PROJECT_SOURCE_DIR}/package/deb/scripts/postinst.in)
set(DEBIAN_CONTROL_POSTINST_FILE ${CMAKE_CURRENT_BINARY_DIR}/postinst)
configure_file(
     ${DEBIAN_CONTROL_POSTINST_TEMPLATE}
     ${DEBIAN_CONTROL_POSTINST_FILE}
     @ONLY
)

set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
     ${PROJECT_SOURCE_DIR}/LICENSE.txt
     ${PROJECT_SOURCE_DIR}/package/deb/scripts/preinst
     ${DEBIAN_CONTROL_POSTINST_FILE}
     )

include(CPack)
