name: CMake

# Реагируем на любой push в любую ветку
on: [push]

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo (without submodules)
      uses: actions/checkout@v2

    - name: Generate documentation
      uses: langroodi/doxygenize@v1.5
      with:
        htmloutput: ./doc

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
    - name: Checkout repo with submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Install required packages
      run: xargs sudo apt-get install --yes < requirements.txt

    - name: Configure project
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build project
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}} --parallel $(nproc)

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build-type}}
