name: Generate Doxygen
on: [push]
jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo (without submodules)
      uses: actions/checkout@v2
      
    - name: Generate documentation
      uses: langroodi/doxygenize@v1.7.0
      with:
        darkmode: false
        # Указание данного пути заставляет action копировать HTML-документацию
        # в корень ветки gh-pages.
        # Таким образом файл index.html оказывается в корневой директории и корректно
        # работает ссылка https://alexen.github.io/using_boost
        htmloutput: ./doc/html
